web:
  upload-path: d://file


server:
  port: 8000

spring:
  resources:
    static-locations: file:${web.upload-path}

  mvc:
    formcontent:
      putfilter:
        enabled: true

  jmx:
    enabled: true

  datasource:
    url: jdbc:mysql://bj-cdb-hgkqwllz.sql.tencentcdb.com:63308/test_tb?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: wtdbuser
    password: wtdbuser
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 50MB

  redis:
    host: localhost
    port: 1024
    database: 0
    jedis:
      pool:
        min-idle: 5
        max-idle: 10




mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.magicreal.module.bean
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  path: d://file/log
  level:
    lombok.core.debug: debug

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true
  row-bounds-with-count: true
